name: CI

on:
  push:
    branches:
      - master  # Change this to your default branch
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'  # Initialize and update submodules

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.28'  # Specify your required CMake version

      - name: Build in Release mode
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Run tests
        run: |
          cd build/MyTest
          ctest -C Release

      # - name: Upload test results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: test-results-${{ matrix.os }}
      #     path: build/Testing/Temporary/*
